/*
Product: OpenXT
Project: Synchronizer Administration Web UI
Copyright© Citrix 2012
*/

define ({root: {
    // Layout
    SYS_INFO_HEADER: "Settings",
    DETAILS: "Details",
    NAME_LABEL: "Name:",
    NAME_VALERROR: "Name is required",
    UUID_LABEL: "UUID:",
    REPO_LABEL: "Repository:",
    USER_LABEL: "User:",
    SELECT_USER_ACTION: "Select User",
    REMOVE_USER_ACTION: "Remove User",
    REMOVE_USER_WARNING: "Are you sure you want to remove this user from the computer?",
    ADD_USER_ERROR: "There was an error adding this user.",
    NONE_SET: "None Set",
    SYS_INFO_WALLPAPER_TITLE: "Wallpaper",
    WALLPAPER_HEADER: "Select a wallpaper for the client",
    WALLPAPER_OVERRIDE_HEADER: "To use a wallpaper not listed enter the client filepath below",
    WALLPAPER_TEXT_LABEL: "Wallpaper Path:",
    CLOSE_ACTION: "Cancel",
    SAVE_ACTION: "Save",
    NOT_SET: "Not Included",
    CONFIGURATION: "Xenmgr Config",
    AUTOSTART_LABEL: "Autostart:",
    VM_CREATION_ALLOWED_LABEL: "VM Creation Allowed:",
    VM_DELETION_ALLOWED_LABEL: "VM Deletion Allowed:",
    OTA_UPGRADES_ALLOWED_LABEL: "OTA Upgrades Allowed:",
    CONNECT_REMOTE_DESKTOP_ALLOWED_LABEL: "Allow Remote Desktop",
    MEASURE_FAIL_ACTION_LABEL: "Measure Fail Action:",
    NOTHING_ACTION: "Nothing",
    SLEEP_ACTION: "Sleep",
    HIBERNATE_ACTION: "Hibernate",
    REBOOT_ACTION: "Reboot",
    SHUTDOWN_ACTION: "Shutdown",
    FORCE_SHUTDOWN_ACTION: "Force Shutdown",
    V4V_FIREWALL_LABEL: "V4V Firewall Enabled:",
    ENABLE_SSH_LABEL: "External SSH Enabled:",
    ENABLE_V4V_SSH_LABEL: "Internal (v4v) SSH Enabled:",
    ENABLE_DOM0_NETWORKING_LABEL: "Dom0 Networking Enabled:",
    CUSTOM: "Custom",
    ADD_ACTION: "Add",
    DAEMON: "Daemon",
    PROPERTY: "Property",
    VALUE: "Value",
    REMOVE_ACTION: "Remove",
    UI_CONFIG: "UI Config",
    LANGUAGE_LABEL: "Language",
    SHOW_MSG_ON_VM_START_LABEL: "Show VM Start Message:",
    SHOW_MSG_ON_VM_START_TOOLS_WARNING_LABEL: "Show VM Start Tools Warning:",
    SHOW_MSG_ON_NO_DISK_LABEL: "Show Message on Deleting Last Disk",
    SHOW_MBOOT_WARNING_LABEL: "Show Measured Boot Warning",
    SHOW_TOOLS_WARNING_LABEL: "Show Tools Warning",
    MODIFY_SETTINGS_LABEL: "Can Modify Settings:",
    MODIFY_SERVICES_LABEL: "Can Modify Service:",
    NO_CUSTOM_FIELDS: "No custom fields defined",
    MODIFY_ADVANCED_VM_SETTINGS_LABEL: "Can Modify VM:",
    SELECT_USER_TITLE: "Select User",
    REPLACE_CONFIG_MESSAGE: "This will overwrite the existing computer configurations. Do you wish to continue?",
    REPLACE_ACTION: "Replace"
}});